inherit_from:
  - ../../.rubocop.yml

AllCops:
  Exclude:
    - biform.gemspec
    - Gemfile
    - Gemfile.lock
    - README.md

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Security/Eval:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Lint/UnneededCopDisableDirective:
  Enabled: false

